name: Cross Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build/Release
      run: ./type_check.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./type_check

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./type_check

  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: Create build directory
      run: mkdir -p ${{github.workspace}}/build
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
        -GXcode \
        -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/ios.toolchain.cmake \
        -DPLATFORM=OS64 \
        -DENABLE_BITCODE=OFF \
        -DENABLE_ARC=OFF \
        -DDEPLOYMENT_TARGET=13.0 \
        -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build \
        --config Release \
        -- \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Install NDK
      run: |
        yes | sdkmanager --install "ndk;25.2.9519653"
        echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
    - name: Create build directory
      run: mkdir -p ${{github.workspace}}/build
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
        -DCMAKE_TOOLCHAIN_FILE=${{env.ANDROID_NDK_ROOT}}/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-21 \
        -DANDROID_STL=c++_shared \
        -DANDROID_CPP_FEATURES="rtti exceptions" \
        -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release